# Generated by Django 5.2.8 on 2026-02-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        ('huertos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('sembrado', 'Sembrado'), ('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('maduracion', 'Maduración'), ('listo', 'Listo para cosecha'), ('cosechado', 'Cosechado'), ('muerta_sequia', 'Muerta por sequía'), ('muerta_ahogo', 'Muerta por ahogo'), ('pasada', 'Pasada')], default='sembrado', max_length=50)),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('ultimo_riego', models.DateField(blank=True, null=True)),
                ('proximo_riego', models.DateField(blank=True, null=True)),
                ('veces_regada_hoy', models.IntegerField(default=0)),
                ('fecha_ultimo_reset', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cultivo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivotipo')),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huertos.huerto')),
            ],
        ),
    ]
