# Generated by Django 5.2.8 on 2026-02-28 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacion',
            name='fecha_siembra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
