# Generated by Django 5.2.8 on 2026-02-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultivoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_dias', models.IntegerField()),
                ('requerimiento_agua_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia_siembra_cm', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
            ],
        ),
    ]
