# Generated by Django 5.2.8 on 2026-02-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('plantacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='plantacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='plantacion.plantacion'),
        ),
    ]
